name: Update Gallery List

on:
  push:
    paths:
      - 'media/**'   # Папкадагы файлдар өзгөргөндө иштейт
  workflow_dispatch:          # Кол менен да иштетсе болот

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate gallery.json
        run: |
          echo "[" > gallery.json
          find images/gallery -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.gif" \) \
          | sed 's/"/\\"/g' | sed 's/^/  "/;s/$/",/' >> gallery.json
          sed -i '$ s/,$//' gallery.json
          echo "]" >> gallery.json

      - name: Commit and push gallery.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add gallery.json
          git commit -m "Update gallery list"
          git push
